/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type NavSection = {
  _type: "navSection";
  hideSection?: boolean;
  hideOnDesktop?: boolean;
  heading?: string;
  links?: Array<{
    _key: string;
  } & VerticalNavLink>;
};

export type VerticalNavDivider = {
  _type: "verticalNavDivider";
  hideOnDesktop?: boolean;
  style?: string;
};

export type VerticalNavLink = {
  _type: "verticalNavLink";
  hideLink?: boolean;
  hideOnDesktop?: boolean;
  label?: string;
  linkType?: "internal" | "external";
  internalLink?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "homePage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "blogIndexPage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "blogPost";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "termsAndConditions";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "privacyPolicy";
  };
  externalUrl?: string;
  pageSectionId?: string;
  openInNewTab?: boolean;
};

export type NavLink = {
  _type: "navLink";
  hideLink?: boolean;
  label?: string;
  linkType?: "internal" | "external";
  internalLink?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "homePage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "blogIndexPage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "blogPost";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "termsAndConditions";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "privacyPolicy";
  };
  externalUrl?: string;
  pageSectionId?: string;
  openInNewTab?: boolean;
};

export type CtaList = Array<{
  _key: string;
} & EmbeddedCtaButton>;

export type CompanyLinksArray = {
  _type: "companyLinksArray";
  socialLinksArray?: Array<{
    url?: string;
    detectedPlatform?: string;
    platform?: "genericLink";
    customTitle?: string;
    hideFromFooter?: boolean;
    _type: "socialLinkItem";
    _key: string;
  }>;
};

export type ContactForm = {
  _type: "contactForm";
  placeholder?: string;
};

export type FeaturedProjects = {
  _type: "featuredProjects";
  projects?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "project";
  }>;
};

export type ProjectList = {
  _type: "projectList";
  placeholder?: string;
};

export type TeamMemberList = {
  _type: "teamMemberList";
  category?: "primary" | "secondary";
  displayStyle?: "detailed" | "condensed";
};

export type ClientList = {
  _type: "clientList";
  placeholder?: string;
};

export type EquipmentList = {
  _type: "equipmentList";
  placeholder?: string;
};

export type ItemList = {
  _type: "itemList";
  alignment?: "inherit" | "left" | "center" | "right";
  items?: Array<{
    text?: string;
    icon?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    _type: "listItem";
    _key: string;
  }>;
};

export type CheckList = {
  _type: "checkList";
  items?: Array<{
    text?: string;
    _type: "checkListItem";
    _key: string;
  }>;
};

export type BlockListWithStats = {
  _type: "blockListWithStats";
  items?: Array<{
    leftContent?: string;
    rightContent?: string;
    _type: "blockListItem";
    _key: string;
  }>;
};

export type CompanyLinksBlock = {
  _type: "companyLinksBlock";
  blockAdded?: string;
};

export type CtaBlogPost = {
  _type: "ctaBlogPost";
  blogPost?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "blogPost";
  };
};

export type HomeHeroCtaButton = {
  _type: "homeHeroCtaButton";
  text?: string;
  linkType?: "internal" | "external";
  internalLink?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "homePage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "blogIndexPage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "blogPost";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "termsAndConditions";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "privacyPolicy";
  };
  externalUrl?: string;
  pageSectionId?: string;
  openInNewTab?: boolean;
};

export type EmbeddedCtaButton = {
  _type: "embeddedCtaButton";
  text?: string;
  variant?: "filled" | "outline-light" | "outline-dark" | "text-link";
  linkType?: "internal" | "external";
  internalLink?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "homePage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "blogIndexPage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "blogPost";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "termsAndConditions";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "privacyPolicy";
  };
  externalUrl?: string;
  pageSectionId?: string;
  openInNewTab?: boolean;
};

export type CtaCalloutLink = {
  _type: "ctaCalloutLink";
  heading?: string;
  text?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  linkType?: "internal" | "external";
  internalLink?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "homePage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "blogIndexPage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "blogPost";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "termsAndConditions";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "privacyPolicy";
  };
  externalUrl?: string;
  pageSectionId?: string;
  openInNewTab?: boolean;
};

export type CtaButton = {
  _type: "ctaButton";
  text?: string;
  variant?: "filled" | "outline-light" | "outline-dark" | "text-link";
  alignment?: "inherit" | "left" | "center" | "right";
  linkType?: "internal" | "external";
  internalLink?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "homePage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "blogIndexPage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "blogPost";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "termsAndConditions";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "privacyPolicy";
  };
  externalUrl?: string;
  pageSectionId?: string;
  openInNewTab?: boolean;
};

export type TwoColumnLayout = {
  _type: "twoColumnLayout";
  verticallyCenter?: boolean;
  leftColumn?: Array<{
    _key: string;
  } & Divider | {
    _key: string;
  } & RichText | {
    _key: string;
  } & BlockListWithStats | {
    _key: string;
  } & CheckList | {
    _key: string;
  } & EquipmentList | {
    _key: string;
  } & ProjectList | {
    _key: string;
  } & FeaturedProjects | {
    _key: string;
  } & ContactForm | {
    _key: string;
  } & Quote | {
    _key: string;
  } & ImageBlock | {
    _key: string;
  } & ImageGallery | {
    _key: string;
  } & ImageGroup | {
    _key: string;
  } & CtaButton | {
    _key: string;
  } & CtaCalloutLink | {
    _key: string;
  } & CtaBlogPost | {
    _key: string;
  } & Card | {
    _key: string;
  } & GridLayout | {
    _key: string;
  } & YouTubeVideo | {
    _key: string;
  } & SpotifyWidget | {
    _key: string;
  } & BandcampWidget | {
    _key: string;
  } & AudioSamplePlayer | {
    _key: string;
  } & CompanyLinksBlock>;
  rightColumn?: Array<{
    _key: string;
  } & Divider | {
    _key: string;
  } & RichText | {
    _key: string;
  } & BlockListWithStats | {
    _key: string;
  } & CheckList | {
    _key: string;
  } & EquipmentList | {
    _key: string;
  } & ProjectList | {
    _key: string;
  } & FeaturedProjects | {
    _key: string;
  } & ContactForm | {
    _key: string;
  } & Quote | {
    _key: string;
  } & ImageBlock | {
    _key: string;
  } & ImageGallery | {
    _key: string;
  } & ImageGroup | {
    _key: string;
  } & CtaButton | {
    _key: string;
  } & CtaCalloutLink | {
    _key: string;
  } & CtaBlogPost | {
    _key: string;
  } & Card | {
    _key: string;
  } & GridLayout | {
    _key: string;
  } & YouTubeVideo | {
    _key: string;
  } & SpotifyWidget | {
    _key: string;
  } & BandcampWidget | {
    _key: string;
  } & AudioSamplePlayer | {
    _key: string;
  } & CompanyLinksBlock>;
};

export type Quote = {
  _type: "quote";
  text?: string;
  attribution?: string;
  textAlign?: "inherit" | "left" | "center" | "right";
};

export type AudioSamplePlayer = {
  _type: "audioSamplePlayer";
  audioSamples?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "audioSample";
  }>;
};

export type BandcampWidget = {
  _type: "bandcampWidget";
  embedCode?: string;
};

export type SpotifyWidget = {
  _type: "spotifyWidget";
  embedCode?: string;
};

export type YouTubeVideo = {
  _type: "youTubeVideo";
  url?: string;
};

export type ImageGroup = {
  _type: "imageGroup";
  images?: Array<{
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    _type: "imageGroupItem";
    _key: string;
  }>;
  size?: "full" | "small";
  duration?: number;
};

export type ImageGallery = {
  _type: "imageGallery";
  columns?: "2" | "3" | "4";
  showCaptionsBelowImages?: boolean;
  images?: Array<{
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    caption?: string;
    _key: string;
  }>;
};

export type ImageBlock = {
  _type: "imageBlock";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  size?: "full" | "small";
  caption?: string;
};

export type Icon = {
  _type: "icon";
  showIcon?: boolean;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type GridLayout = {
  _type: "gridLayout";
  columns?: "2" | "3" | "4";
  content?: Array<{
    _key: string;
  } & RichText | {
    _key: string;
  } & EquipmentList | {
    _key: string;
  } & ProjectList | {
    _key: string;
  } & FeaturedProjects | {
    _key: string;
  } & Card | {
    _key: string;
  } & ImageBlock | {
    _key: string;
  } & ImageGroup | {
    _key: string;
  } & YouTubeVideo | {
    _key: string;
  } & SpotifyWidget | {
    _key: string;
  } & BandcampWidget | {
    _key: string;
  } & AudioSamplePlayer>;
};

export type Card = {
  _type: "card";
  visualStyle?: "light" | "dark";
  title?: string;
  subtitle?: string;
  imageType?: "none" | "banner" | "icon";
  iconNoImageLayoutStyle?: "stacked" | "row";
  iconSelection?: "acoustics" | "location" | "mic" | "equipment" | "phone" | "email" | "facebook" | "guitar" | "speaker" | "computer" | "cog" | "software";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  content?: Array<{
    _key: string;
  } & Divider | {
    _key: string;
  } & TwoColumnLayout | {
    _key: string;
  } & RichText | {
    _key: string;
  } & BlockListWithStats | {
    _key: string;
  } & CheckList | {
    _key: string;
  } & Quote | {
    _key: string;
  } & ImageBlock | {
    _key: string;
  } & ImageGallery | {
    _key: string;
  } & ImageGroup | {
    _key: string;
  } & CtaButton | {
    _key: string;
  } & CtaCalloutLink | {
    _key: string;
  } & CtaBlogPost | {
    _key: string;
  } & YouTubeVideo | {
    _key: string;
  } & SpotifyWidget | {
    _key: string;
  } & BandcampWidget | {
    _key: string;
  } & CompanyLinksBlock>;
};

export type RichText = {
  _type: "richText";
  isCallout?: boolean;
  textAlign?: "inherit" | "left" | "center" | "right";
  content?: BlockContent;
};

export type Divider = {
  _type: "divider";
  style?: string;
};

export type SubSubSection = {
  _type: "subSubSection";
  hideSection?: boolean;
  title?: string;
  titleTranslation?: string;
  anchorId?: string;
  content?: Array<{
    _key: string;
  } & Divider | {
    _key: string;
  } & TwoColumnLayout | {
    _key: string;
  } & GridLayout | {
    _key: string;
  } & RichText | {
    _key: string;
  } & BlockListWithStats | {
    _key: string;
  } & CheckList | {
    _key: string;
  } & ItemList | {
    _key: string;
  } & EquipmentList | {
    _key: string;
  } & ClientList | {
    _key: string;
  } & TeamMemberList | {
    _key: string;
  } & ProjectList | {
    _key: string;
  } & FeaturedProjects | {
    _key: string;
  } & ContactForm | {
    _key: string;
  } & Quote | {
    _key: string;
  } & ImageBlock | {
    _key: string;
  } & ImageGallery | {
    _key: string;
  } & ImageGroup | {
    _key: string;
  } & CtaButton | {
    _key: string;
  } & CtaCalloutLink | {
    _key: string;
  } & CtaBlogPost | {
    _key: string;
  } & Card | {
    _key: string;
  } & YouTubeVideo | {
    _key: string;
  } & SpotifyWidget | {
    _key: string;
  } & BandcampWidget | {
    _key: string;
  } & AudioSamplePlayer | {
    _key: string;
  } & CompanyLinksBlock>;
};

export type SubSection = {
  _type: "subSection";
  hideSection?: boolean;
  title?: string;
  titleTranslation?: string;
  anchorId?: string;
  content?: Array<{
    _key: string;
  } & SubSubSection | {
    _key: string;
  } & Divider | {
    _key: string;
  } & TwoColumnLayout | {
    _key: string;
  } & GridLayout | {
    _key: string;
  } & RichText | {
    _key: string;
  } & BlockListWithStats | {
    _key: string;
  } & CheckList | {
    _key: string;
  } & ItemList | {
    _key: string;
  } & EquipmentList | {
    _key: string;
  } & ClientList | {
    _key: string;
  } & TeamMemberList | {
    _key: string;
  } & ProjectList | {
    _key: string;
  } & FeaturedProjects | {
    _key: string;
  } & ContactForm | {
    _key: string;
  } & Quote | {
    _key: string;
  } & ImageBlock | {
    _key: string;
  } & ImageGallery | {
    _key: string;
  } & ImageGroup | {
    _key: string;
  } & CtaButton | {
    _key: string;
  } & CtaCalloutLink | {
    _key: string;
  } & CtaBlogPost | {
    _key: string;
  } & Card | {
    _key: string;
  } & YouTubeVideo | {
    _key: string;
  } & SpotifyWidget | {
    _key: string;
  } & BandcampWidget | {
    _key: string;
  } & AudioSamplePlayer | {
    _key: string;
  } & CompanyLinksBlock>;
};

export type PageSection = {
  _type: "pageSection";
  hideSection?: boolean;
  title?: string;
  titleTranslation?: string;
  subtitle?: string;
  topText?: string;
  useCompactGap?: boolean;
  anchorId?: string;
  content?: Array<{
    _key: string;
  } & SubSection | {
    _key: string;
  } & Divider | {
    _key: string;
  } & TwoColumnLayout | {
    _key: string;
  } & GridLayout | {
    _key: string;
  } & RichText | {
    _key: string;
  } & BlockListWithStats | {
    _key: string;
  } & CheckList | {
    _key: string;
  } & ItemList | {
    _key: string;
  } & EquipmentList | {
    _key: string;
  } & ClientList | {
    _key: string;
  } & TeamMemberList | {
    _key: string;
  } & ProjectList | {
    _key: string;
  } & FeaturedProjects | {
    _key: string;
  } & ContactForm | {
    _key: string;
  } & Quote | {
    _key: string;
  } & ImageBlock | {
    _key: string;
  } & ImageGallery | {
    _key: string;
  } & ImageGroup | {
    _key: string;
  } & CtaButton | {
    _key: string;
  } & CtaCalloutLink | {
    _key: string;
  } & CtaBlogPost | {
    _key: string;
  } & Card | {
    _key: string;
  } & YouTubeVideo | {
    _key: string;
  } & SpotifyWidget | {
    _key: string;
  } & BandcampWidget | {
    _key: string;
  } & AudioSamplePlayer | {
    _key: string;
  } & CompanyLinksBlock>;
};

export type PageBuilder = Array<{
  _key: string;
} & PageSection | {
  _key: string;
} & Divider | {
  _key: string;
} & TwoColumnLayout | {
  _key: string;
} & GridLayout | {
  _key: string;
} & RichText | {
  _key: string;
} & BlockListWithStats | {
  _key: string;
} & CheckList | {
  _key: string;
} & ItemList | {
  _key: string;
} & EquipmentList | {
  _key: string;
} & ClientList | {
  _key: string;
} & TeamMemberList | {
  _key: string;
} & ProjectList | {
  _key: string;
} & FeaturedProjects | {
  _key: string;
} & ContactForm | {
  _key: string;
} & Quote | {
  _key: string;
} & ImageBlock | {
  _key: string;
} & ImageGallery | {
  _key: string;
} & ImageGroup | {
  _key: string;
} & CtaButton | {
  _key: string;
} & CtaCalloutLink | {
  _key: string;
} & CtaBlogPost | {
  _key: string;
} & Card | {
  _key: string;
} & YouTubeVideo | {
  _key: string;
} & SpotifyWidget | {
  _key: string;
} & BandcampWidget | {
  _key: string;
} & AudioSamplePlayer | {
  _key: string;
} & CompanyLinksBlock>;

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  footerMessages?: Array<{
    title?: string;
    message?: string;
    _key: string;
  }>;
  quickLinks?: Array<{
    label?: string;
    linkType?: "internal" | "external";
    internalLink?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "page";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "homePage";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "blogIndexPage";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "blogPost";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "termsAndConditions";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "privacyPolicy";
    };
    externalUrl?: string;
    pageSectionId?: string;
    openInNewTab?: boolean;
    _key: string;
  }>;
};

export type Header = {
  _id: string;
  _type: "header";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  horizontalNav?: Array<{
    _key: string;
  } & NavLink>;
  verticalNav?: Array<{
    _key: string;
  } & NavSection>;
  verticalNavCtas?: CtaList;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "body-3xl" | "body-2xl" | "body-xl" | "body-lg" | "body-sm" | "body-xs" | "standout";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  } | {
    _key: string;
  } & Color>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type PrivacyPolicy = {
  _id: string;
  _type: "privacyPolicy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hide?: boolean;
  title?: string;
  titleTeReo?: string;
  topText?: string;
  content?: Array<{
    _key: string;
  } & PageSection | {
    _key: string;
  } & Divider | {
    _key: string;
  } & TwoColumnLayout | {
    _key: string;
  } & GridLayout | {
    _key: string;
  } & RichText | {
    _key: string;
  } & BlockListWithStats | {
    _key: string;
  } & CheckList | {
    _key: string;
  } & ItemList | {
    _key: string;
  } & EquipmentList | {
    _key: string;
  } & ClientList | {
    _key: string;
  } & TeamMemberList | {
    _key: string;
  } & ProjectList | {
    _key: string;
  } & FeaturedProjects | {
    _key: string;
  } & ContactForm | {
    _key: string;
  } & Quote | {
    _key: string;
  } & ImageBlock | {
    _key: string;
  } & ImageGallery | {
    _key: string;
  } & ImageGroup | {
    _key: string;
  } & CtaButton | {
    _key: string;
  } & CtaCalloutLink | {
    _key: string;
  } & CtaBlogPost | {
    _key: string;
  } & Card | {
    _key: string;
  } & YouTubeVideo | {
    _key: string;
  } & SpotifyWidget | {
    _key: string;
  } & BandcampWidget | {
    _key: string;
  } & AudioSamplePlayer | {
    _key: string;
  } & CompanyLinksBlock>;
};

export type TermsAndConditions = {
  _id: string;
  _type: "termsAndConditions";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hide?: boolean;
  title?: string;
  titleTeReo?: string;
  topText?: string;
  content?: Array<{
    _key: string;
  } & PageSection | {
    _key: string;
  } & Divider | {
    _key: string;
  } & TwoColumnLayout | {
    _key: string;
  } & GridLayout | {
    _key: string;
  } & RichText | {
    _key: string;
  } & BlockListWithStats | {
    _key: string;
  } & CheckList | {
    _key: string;
  } & ItemList | {
    _key: string;
  } & EquipmentList | {
    _key: string;
  } & ClientList | {
    _key: string;
  } & TeamMemberList | {
    _key: string;
  } & ProjectList | {
    _key: string;
  } & FeaturedProjects | {
    _key: string;
  } & ContactForm | {
    _key: string;
  } & Quote | {
    _key: string;
  } & ImageBlock | {
    _key: string;
  } & ImageGallery | {
    _key: string;
  } & ImageGroup | {
    _key: string;
  } & CtaButton | {
    _key: string;
  } & CtaCalloutLink | {
    _key: string;
  } & CtaBlogPost | {
    _key: string;
  } & Card | {
    _key: string;
  } & YouTubeVideo | {
    _key: string;
  } & SpotifyWidget | {
    _key: string;
  } & BandcampWidget | {
    _key: string;
  } & AudioSamplePlayer | {
    _key: string;
  } & CompanyLinksBlock>;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: string;
  linkLabel?: string;
  link?: string;
  order?: number;
};

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  category?: "primary" | "secondary";
  profilePicture?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  displayOrder?: number;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "body-xs" | "body-sm" | "body-lg" | "body-xl" | "body-2xl" | "body-3xl" | "standout";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type EquipmentListSingleton = {
  _id: string;
  _type: "equipmentListSingleton";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  categories?: Array<{
    name?: string;
    icon?: "acoustics" | "location" | "mic" | "equipment" | "phone" | "email" | "facebook" | "guitar" | "speaker" | "computer" | "cog" | "software";
    items?: Array<{
      name?: string;
      isTemporarilyUnavailable?: boolean;
      unavailableReason?: string;
      _type: "equipmentItem";
      _key: string;
    }>;
    _type: "equipmentCategory";
    _key: string;
  }>;
};

export type Clients = {
  _id: string;
  _type: "clients";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  level1?: Array<string>;
  level2?: Array<string>;
  level3?: Array<string>;
  level4?: Array<string>;
  level5?: Array<string>;
};

export type AudioSample = {
  _id: string;
  _type: "audioSample";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  songName?: string;
  artistName?: string;
  services?: Array<string>;
  audioFile?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
};

export type BlogPost = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  subtitle?: string;
  author?: string;
  currentPublicationDate?: string;
  hasOverrideDate?: boolean;
  overrideDate?: string;
  content?: Array<{
    _key: string;
  } & PageSection | {
    _key: string;
  } & Divider | {
    _key: string;
  } & TwoColumnLayout | {
    _key: string;
  } & GridLayout | {
    _key: string;
  } & RichText | {
    _key: string;
  } & BlockListWithStats | {
    _key: string;
  } & CheckList | {
    _key: string;
  } & ItemList | {
    _key: string;
  } & EquipmentList | {
    _key: string;
  } & ClientList | {
    _key: string;
  } & TeamMemberList | {
    _key: string;
  } & ProjectList | {
    _key: string;
  } & FeaturedProjects | {
    _key: string;
  } & ContactForm | {
    _key: string;
  } & Quote | {
    _key: string;
  } & ImageBlock | {
    _key: string;
  } & ImageGallery | {
    _key: string;
  } & ImageGroup | {
    _key: string;
  } & CtaButton | {
    _key: string;
  } & CtaCalloutLink | {
    _key: string;
  } & CtaBlogPost | {
    _key: string;
  } & Card | {
    _key: string;
  } & YouTubeVideo | {
    _key: string;
  } & SpotifyWidget | {
    _key: string;
  } & BandcampWidget | {
    _key: string;
  } & AudioSamplePlayer | {
    _key: string;
  } & CompanyLinksBlock>;
  hasClosingCard?: boolean;
  closingCard?: Card;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type BlogIndexPage = {
  _id: string;
  _type: "blogIndexPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleTeReo?: string;
  subtitle?: string;
  noArticlesMessage?: string;
  hasClosingCard?: boolean;
  closingCard?: Card;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  titleTeReo?: string;
  subtitle?: string;
  content?: Array<{
    _key: string;
  } & PageSection | {
    _key: string;
  } & Divider | {
    _key: string;
  } & TwoColumnLayout | {
    _key: string;
  } & GridLayout | {
    _key: string;
  } & RichText | {
    _key: string;
  } & BlockListWithStats | {
    _key: string;
  } & CheckList | {
    _key: string;
  } & ItemList | {
    _key: string;
  } & EquipmentList | {
    _key: string;
  } & ClientList | {
    _key: string;
  } & TeamMemberList | {
    _key: string;
  } & ProjectList | {
    _key: string;
  } & FeaturedProjects | {
    _key: string;
  } & ContactForm | {
    _key: string;
  } & Quote | {
    _key: string;
  } & ImageBlock | {
    _key: string;
  } & ImageGallery | {
    _key: string;
  } & ImageGroup | {
    _key: string;
  } & CtaButton | {
    _key: string;
  } & CtaCalloutLink | {
    _key: string;
  } & CtaBlogPost | {
    _key: string;
  } & Card | {
    _key: string;
  } & YouTubeVideo | {
    _key: string;
  } & SpotifyWidget | {
    _key: string;
  } & BandcampWidget | {
    _key: string;
  } & AudioSamplePlayer | {
    _key: string;
  } & CompanyLinksBlock>;
  hasClosingCard?: boolean;
  closingCard?: Card;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroStyle?: "default" | "background-images";
  heroBackgroundImages?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  heroImageTransitionDuration?: number;
  heroTextColor?: "black" | "white";
  heroContentPosition?: "top-left" | "top-center" | "top-right" | "center-left" | "center-center" | "center-right" | "bottom-left" | "bottom-center" | "bottom-right";
  heroLogoDisplay?: "none" | "with-text" | "logo-only";
  h1Title?: string;
  heroTitle?: BlockContent;
  heroCallToActionList?: CtaList;
  hideScrollIndicator?: boolean;
  content?: PageBuilder;
};

export type ContactFormSettings = {
  _id: string;
  _type: "contactFormSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  subtitle?: string;
  messagePlaceholder?: string;
  successHeading?: string;
  successMessage?: string;
  emailGreeting?: string;
  emailIntroMessage?: string;
  emailOutroMessage?: string;
};

export type CompanyLinks = {
  _id: string;
  _type: "companyLinks";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  companyLinks?: CompanyLinksArray;
};

export type SeoMetaData = {
  _id: string;
  _type: "seoMetaData";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle?: string;
  siteTagline?: string;
  siteDescription?: string;
  seoKeywords?: string;
  defaultOgImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type BusinessInfo = {
  _id: string;
  _type: "businessInfo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  organisationName?: string;
  organisationDescription?: string;
  favicon?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  email?: {
    value?: string;
    link?: string;
  };
  phone?: {
    value?: string;
    link?: string;
  };
  address?: {
    value?: string;
    link?: string;
  };
  businessLocation?: {
    streetAddress?: string;
    addressLocality?: string;
    postalCode?: string;
    addressRegion?: string;
    addressCountry?: string;
    latitude?: string;
    longitude?: string;
    regionCode?: string;
  };
  businessHours?: string;
  priceRange?: string;
  serviceAreas?: Array<{
    type?: string;
    name?: string;
    _key: string;
  }>;
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = NavSection | VerticalNavDivider | VerticalNavLink | NavLink | CtaList | CompanyLinksArray | ContactForm | FeaturedProjects | ProjectList | TeamMemberList | ClientList | EquipmentList | ItemList | CheckList | BlockListWithStats | CompanyLinksBlock | CtaBlogPost | HomeHeroCtaButton | EmbeddedCtaButton | CtaCalloutLink | CtaButton | TwoColumnLayout | Quote | AudioSamplePlayer | BandcampWidget | SpotifyWidget | YouTubeVideo | ImageGroup | ImageGallery | ImageBlock | Icon | SanityImageCrop | SanityImageHotspot | GridLayout | Card | RichText | Divider | SubSubSection | SubSection | PageSection | PageBuilder | Footer | Header | BlockContent | PrivacyPolicy | TermsAndConditions | Project | TeamMember | EquipmentListSingleton | Clients | AudioSample | BlogPost | Slug | BlogIndexPage | Page | HomePage | ContactFormSettings | CompanyLinks | SeoMetaData | BusinessInfo | Color | RgbaColor | HsvaColor | HslaColor | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
